### ISSUE TITLE
Cannot find module 'bindings-ts'

### ISSUE THREAD

**Issue by jvbianchi** [supergraphql/graphql-cli-prepare#57]
When I run `graphql prepare` I get this error:
`Cannot find module 'bindings-ts'`

My .graphqlconfig.yml: 
```yml
projects:
  api:
    schemaPath: "src/schema/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
      prepare-bundle: src/generated/api.graphql
      prepare-binding:
        output: src/generated/api.ts
        generator: bindings-ts
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```
