### ISSUE TITLE
-o flag is ignored

### ISSUE THREAD

**Issue by terion-name** [supergraphql/graphql-cli-prepare#90]
```
$ node_modules/.bin/graphql prepare -p test-dosvit-app-prisma-local -o src/experiments -g graphcool-ts --bindings --save
✔ Bindings for project database written to src/generated/prisma.ts
```

**Comment by kbrandwijk** [comment]
Did you already have existing settings in your .graphqlconfig file?

**Comment by terion-name** [comment]
@kbrandwijk  .graphqlconfig contents:
```
projects:
  app:
    schemaPath: "src/schema.graphql"
    includes: ["queries/{booking,queries}.graphql"]
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    includes: ["database/seed.graphql"]
    extensions:
      prisma: database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```

But here I run cli manually for a different src and different output, set explicitly in arguments, they should have higher priority over config. Moreover, src and output are described only for one of the projects, described in config, and in cli call I don't reference it. If the config is used, than what is the logic, why it takes second project's configuration?
